### ISSUE TITLE
when the container startup , it ask to input [sudo] password

### ISSUE THREAD

**Issue by bao3** [Calipsoplus/base-container-template#1]
I tried default  as password, but it was incorrect , then I tried non-password , thas's useless ....

<img width="1134" alt="image" src="https://user-images.githubusercontent.com/499205/74288213-c9734880-4d66-11ea-808f-54dc8ad190e7.png">

**Comment by aicampbell** [comment]
Hi,

How are you starting the container? 
Here are the instructions for running the container using python: https://hub.docker.com/r/aicampbell/vnc-ubuntu18-xfce

If you want to run it on the command line, try this: 
sudo docker run -d   --group-add 100 --shm-size 1g -p 3389:3389 -p 5901:5901 -p 6901:6901 aicampbell/vnc-ubuntu18-xfce

Passwordless sudo only works if you are adding group 100
